---
# Variáveis específicas para VMs Windows - SOMENTE INFORMATIVO
# Arquivo: inventories/vmware/group_vars/windows.yml

# Identificação do SO
os_family: "Windows"
os_type: "windows"

# Configurações de classificação Windows
windows_classification:
  # Versões Windows mais comuns
  server_versions:
    - "Windows Server 2019"
    - "Windows Server 2016"
    - "Windows Server 2012"
    - "Windows Server 2022"

  desktop_versions:
    - "Windows 10"
    - "Windows 11"
    - "Windows 7"

  # Edições comuns
  server_editions:
    - "Standard"
    - "Datacenter"
    - "Essentials"

  # Roles típicos do Windows Server
  common_roles:
    - "Domain Controller"
    - "File Server"
    - "Web Server (IIS)"
    - "Database Server"
    - "Application Server"
    - "Print Server"

# Portas padrão Windows para documentação
windows_standard_ports:
  rdp: 3389
  winrm_http: 5985
  winrm_https: 5986
  smb: 445
  dns: 53
  dhcp: 67
  ldap: 389
  ldaps: 636
  kerberos: 88

# Serviços críticos Windows para monitoramento
windows_critical_services:
  - "Server"
  - "Workstation"
  - "Windows Management Instrumentation"
  - "Remote Procedure Call (RPC)"
  - "DCOM Server Process Launcher"
  - "RPC Endpoint Mapper"
  - "Windows Event Log"

# Configurações típicas de recursos Windows
windows_resource_profiles:
  domain_controller:
    min_cpu: 2
    recommended_cpu: 4
    min_memory_gb: 4
    recommended_memory_gb: 8
    min_disk_gb: 60

  file_server:
    min_cpu: 2
    recommended_cpu: 4
    min_memory_gb: 4
    recommended_memory_gb: 8
    min_disk_gb: 100

  web_server:
    min_cpu: 2
    recommended_cpu: 4
    min_memory_gb: 4
    recommended_memory_gb: 8
    min_disk_gb: 40

  database_server:
    min_cpu: 4
    recommended_cpu: 8
    min_memory_gb: 8
    recommended_memory_gb: 16
    min_disk_gb: 100

# Features Windows para análise
windows_features_analysis:
  server_features:
    - ".NET Framework"
    - "PowerShell"
    - "Windows PowerShell ISE"
    - "Failover Clustering"
    - "Hyper-V"
    - "Internet Information Services"

  security_features:
    - "Windows Defender"
    - "BitLocker"
    - "Windows Firewall"
    - "User Account Control"

# Categorização para relatórios
windows_categorization:
  # Baseado no nome/versão do SO
  server_or_desktop: >-
    {%- if 'Server' in (vm_guest_os | default('')) -%}
    server
    {%- else -%}
    desktop
    {%- endif -%}

  # Versão do Windows
  windows_version: >-
    {%- if '2022' in (vm_guest_os | default('')) -%}
    server_2022
    {%- elif '2019' in (vm_guest_os | default('')) -%}
    server_2019
    {%- elif '2016' in (vm_guest_os | default('')) -%}
    server_2016
    {%- elif '2012' in (vm_guest_os | default('')) -%}
    server_2012
    {%- elif '10' in (vm_guest_os | default('')) -%}
    windows_10
    {%- elif '11' in (vm_guest_os | default('')) -%}
    windows_11
    {%- else -%}
    unknown
    {%- endif -%}

# Métricas específicas Windows
windows_metrics:
  # Limites recomendados para Windows
  performance_thresholds:
    cpu_high_usage: 80
    memory_high_usage: 85
    disk_low_space: 15

  # Uptime esperado
  expected_uptime:
    production: "99.9%"
    development: "95%"
    testing: "90%"

# Informações para auditoria
windows_audit_info:
  licensing:
    server_licensing: "Per Core + CAL"
    desktop_licensing: "Per Device/User"

  support_lifecycle:
    server_2022_eol: "2031-10-14"
    server_2019_eol: "2029-01-09"
    server_2016_eol: "2027-01-12"
    windows_10_eol: "2025-10-14"
    windows_11_current: true

# Tags específicas Windows
windows_specific_tags:
  - "os_windows"
  - "requires_licensing"
  - "supports_winrm"
  - "supports_rdp"
